apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-back-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-back-news-service
  template:
    metadata:
      labels:
        app: admin-back-news-service
    spec:
      containers:
        - name: admin-back-service
          image: your-docker-registry/admin-back-news-service:latest
          ports:
            - containerPort: 8000